apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    app: mongodb
    project: roboshop
    tier: db

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
      project: roboshop
      tier: db

  template:
    metadata:
      labels:
        app: mongodb
        project: roboshop
        tier: db

    spec: 
      containers:
      - name: mogodb-container
        image: vvkr/mongodb:v1
        imagePullpolicy: Always

apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
spec:
  selector:
    app: mongodb
    project: roboshop
    tier: db
  ports:
  - protocol: TCP
    port: 27017 #service-port in server
    targetPort: 27017 #container Port
