apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: roboshop
  labels:
    apps: redis
    project: roboshop
    tier: db

spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      project: roboshop
      tier: db
  
  template:
    metadata:
      apps: redis
      project: roboshop
      tier: t1
  spec:
    containers:
    - name: redis
      image: redis
      imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: redis

spec:
  selector:
    apps: redis
    project: roboshop
    tier: t1
  ports:
  - protocol: TCP
    port: 6379 #service-port
    targetPort: 6379 #container-port



  